### ISSUE TITLE
can not get new index from solr when I update corresponding record into the mongo

### ISSUE THREAD

**Issue by licett** [10gen-labs/mongo-connector#253]
With the guide, I  run a solr service with mongo-connector.
I get record index successfully from solr when I insert the record into mongo. However, I can not get anything when I update that record.
Why? Any suggestion would be great.
Thanks.

**Comment by llvtt** [comment]
Can you please provide:

1. The command used to run `mongo-connector` and the config file, if 
you're using one.
2. The logs from `mongo-connector`.
3. Solr logs from when you were running `mongo-connector`.
4. An example of the document you inserted and the update operation that 
doesn't seem to be working

Thanks.

**Comment by licett** [comment]
1.mongo-connector --auto-commit-interval=0 -m 192.168.0.123:27017 -t http://localhost:8983/solr/gettingstarted_shard1_replica1 -d solr_doc_manager -v

2.mongo-connector.log is all about:
"2015-05-20 00:00:02,857 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-05-20 00:00:02,858 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1432059561, 2)
2015-05-20 00:00:02,858 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
"
And when I do a insert, it says 
"2015-05-20 09:20:45,841 [DEBUG] mongo_connector.oplog_manager:235 - OplogThread: Operation for this entry is u
2015-05-20 09:20:45,841 [DEBUG] pysolr:286 - Starting request to 'http://localhost:8983/solr/gettingstarted_shard1_replica2/update/?commit=true' (post) with body 'u'<commit '...
2015-05-20 09:20:45,922 [DEBUG] requests.packages.urllib3.connectionpool:383 - "POST /solr/gettingstarted_shard1_replica2/update/?commit=true HTTP/1.1" 200 None
2015-05-20 09:20:45,922 [INFO] pysolr:316 - Finished 'http://localhost:8983/solr/gettingstarted_shard1_replica2/update/?commit=true' (post) with body 'u'<commit ' in 0.081 seconds.
2015-05-20 09:20:45,923 [DEBUG] pysolr:286 - Starting request to 'http://localhost:8983/solr/gettingstarted_shard1_replica2/select/?q=_id%3A55024e970dd4656673eb0147&wt=json' (get) with body ''...
2015-05-20 09:20:45,936 [DEBUG] requests.packages.urllib3.connectionpool:383 - "GET /solr/gettingstarted_shard1_replica2/select/?q=_id%3A55024e970dd4656673eb0147&wt=json HTTP/1.1" 200 None
2015-05-20 09:20:45,938 [INFO] pysolr:316 - Finished 'http://localhost:8983/solr/gettingstarted_shard1_replica2/select/?q=_id%3A55024e970dd4656673eb0147&wt=json' (get) with body '' in 0.015 seconds.
2015-05-20 09:20:45,938 [DEBUG] pysolr:645 - Found '0' search results.
2015-05-20 09:20:45,939 [DEBUG] pysolr:286 - Starting request to 'http://localhost:8983/solr/gettingstarted_shard1_replica2/update/?commit=true' (post) with body 'u'<commit '...
2015-05-20 09:20:45,972 [DEBUG] requests.packages.urllib3.connectionpool:383 - "POST /solr/gettingstarted_shard1_replica2/update/?commit=true HTTP/1.1" 200 None
2015-05-20 09:20:45,974 [INFO] pysolr:316 - Finished 'http://localhost:8983/solr/gettingstarted_shard1_replica2/update/?commit=true' (post) with body 'u'<commit ' in 0.035 seconds.
2015-05-20 09:20:45,975 [DEBUG] pysolr:286 - Starting request to 'http://localhost:8983/solr/gettingstarted_shard1_replica2/select/?q=_id%3A55024e970dd4656673eb0147&wt=json' (get) with body ''...
2015-05-20 09:20:45,980 [DEBUG] requests.packages.urllib3.connectionpool:383 - "GET /solr/gettingstarted_shard1_replica2/select/?q=_id%3A55024e970dd4656673eb0147&wt=json HTTP/1.1" 200 None
2015-05-20 09:20:45,981 [INFO] pysolr:316 - Finished 'http://localhost:8983/solr/gettingstarted_shard1_replica2/select/?q=_id%3A55024e970dd4656673eb0147&wt=json' (get) with body '' in 0.006 seconds.
2015-05-20 09:20:45,981 [DEBUG] pysolr:645 - Found '0' search results.
2015-05-20 09:20:45,981 [DEBUG] mongo_connector.oplog_manager:290 - OplogThread: Doc is processed.
2015-05-20 09:20:45,982 [DEBUG] mongo_connector.oplog_manager:190 - OplogThread: Iterating through cursor, document number in this cursor is 1
2015-05-20 09:20:45,982 [DEBUG] mongo_connector.oplog_manager:235 - OplogThread: Operation for this entry is i
2015-05-20 09:20:45,982 [DEBUG] pysolr:783 - Starting to build add request...
2015-05-20 09:20:45,983 [DEBUG] pysolr:798 - Built add request of 1 docs in 0.00 seconds.
2015-05-20 09:20:45,983 [DEBUG] pysolr:286 - Starting request to 'http://localhost:8983/solr/gettingstarted_shard1_replica2/update/?commit=false' (post) with body 'u'<add><do'...
2015-05-20 09:20:46,016 [DEBUG] requests.packages.urllib3.connectionpool:383 - "POST /solr/gettingstarted_shard1_replica2/update/?commit=false HTTP/1.1" 200 None
2015-05-20 09:20:46,016 [INFO] pysolr:316 - Finished 'http://localhost:8983/solr/gettingstarted_shard1_replica2/update/?commit=false' (post) with body 'u'<add><do' in 0.033 seconds.
2015-05-20 09:20:46,016 [DEBUG] mongo_connector.oplog_manager:290 - OplogThread: Doc is processed."

4.In mongo , I have a database named "md" with 2 collecions : "realtimedata" and "historydata"
a. update operation
original realtimedata:
{ "_id" : ObjectId("55024e970dd4656673eb0147"), "u" : 90, "v" : 25, "d" : 0, "t" : "2015-05-20 10:17:00", "a" : 0, "l" : [ 31.831942, 117.199812 ], "j" : 0, "h" : 5e-324, "i" : NumberLong(0), "c" : "合肥市", "p" : "安徽省" }

after update operation:
{ "_id" : ObjectId("55024e970dd4656673eb0147"), "u" : 90, "v" : 30, "d" : 0, "t" : "2015-05-20 10:26:39", "a" : 0, "l" : [ 31.831942, 117.199812 ], "j" : 0, "h" : 5e-324, "i" : NumberLong(0), "c" : "合肥市", "p" : "安徽省" }
just a change that v from "25" to "30"

b. insert operation
I insert the last record to history data that:
{ "_id" : ObjectId("555bf0df6c744bb33345aa6a"), "className" : "com.madao.server.common.mongoEntity.HistoryData", "uId" : 90, "teamId" : NumberLong(0), "speed" : 30, "elevation" : 5e-324, "acc" : 0, "loc" : [ 31.831942, 117.199812 ], "province" : "安徽省", "city" : "合肥市", "distance" : 0, "avgSpeed" : 0, "time" : "2015-05-20 10:26:39" }

**Comment by licett** [comment]
3. solr log when mongo connector was running:
INFO  - 2015-05-20 02:38:29.481; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/admin/luke params={numTerms=0&_=1432089509477&show=index&wt=json} status=0 QTime=1 
ERROR - 2015-05-20 02:38:29.486; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.handler.admin.ShowFileRequestHandler; Can not find: /configs/gettingstarted/admin-extra.html
INFO  - 2015-05-20 02:38:29.487; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/admin/file params={file=admin-extra.html&_=1432089509482} status=404 QTime=1 
INFO  - 2015-05-20 02:38:29.492; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/replication params={command=details&_=1432089509479&wt=json} status=0 QTime=11 
INFO  - 2015-05-20 02:38:29.494; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/admin/ping params={action=status&_=1432089509483&wt=json} status=503 QTime=1 
INFO  - 2015-05-20 02:38:29.507; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/admin/system params={_=1432089509480&wt=json} status=0 QTime=23 
INFO  - 2015-05-20 02:38:33.600; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/admin/luke params={show=schema&wt=json} status=0 QTime=5 
INFO  - 2015-05-20 02:40:30.588; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:30.588; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:30.588; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:30.588; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:30.589; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:30.589; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:30.589; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:30.589; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:30.589; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard2_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 2
INFO  - 2015-05-20 02:40:30.589; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 2
INFO  - 2015-05-20 02:40:30.594; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:30.594; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:30.594; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:30.594; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:30.594; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:30.594; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:30.594; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:30.594; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 1
INFO  - 2015-05-20 02:40:30.595; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:30.595; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard2_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 1
INFO  - 2015-05-20 02:40:30.597; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={commit=true} {commit=,commit=} 0 63
INFO  - 2015-05-20 02:40:30.626; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/select params={distrib=false&wt=javabin&version=2&rows=10&df=_text_&fl=id&fl=score&shard.url=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/|http://127.0.1.1:7574/solr/gettingstarted_shard1_replica2/&NOW=1432089630599&start=0&shards.purpose=4&q=_id:55024e970dd4656673eb0147&isShard=true&fsv=true} hits=0 status=0 QTime=10 
INFO  - 2015-05-20 02:40:30.637; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/select params={q=_id:55024e970dd4656673eb0147&wt=json} hits=0 status=0 QTime=38 
INFO  - 2015-05-20 02:40:30.643; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:30.644; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:30.643; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:30.644; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:30.644; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:30.644; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:30.644; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:30.645; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:30.645; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard2_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 2
INFO  - 2015-05-20 02:40:30.645; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 2
INFO  - 2015-05-20 02:40:30.650; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:30.650; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:30.650; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:30.650; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:30.650; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:30.650; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:30.651; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:30.651; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:30.651; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard2_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 2
INFO  - 2015-05-20 02:40:30.651; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 2
INFO  - 2015-05-20 02:40:30.652; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={commit=true} {commit=,commit=} 0 13
INFO  - 2015-05-20 02:40:30.658; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard2_replica1] webapp=/solr path=/select params={distrib=false&wt=javabin&version=2&rows=10&df=_text_&fl=id&fl=score&shard.url=http://127.0.1.1:8983/solr/gettingstarted_shard2_replica1/|http://127.0.1.1:7574/solr/gettingstarted_shard2_replica2/&NOW=1432089630654&start=0&shards.purpose=4&q=_id:55024e970dd4656673eb0147&isShard=true&fsv=true} hits=0 status=0 QTime=1 
INFO  - 2015-05-20 02:40:30.659; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/select params={q=_id:55024e970dd4656673eb0147&wt=json} hits=0 status=0 QTime=4 
INFO  - 2015-05-20 02:40:30.751; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={distrib.from=http://127.0.1.1:7574/solr/gettingstarted_shard1_replica2/&update.distrib=FROMLEADER&wt=javabin&version=2&update.chain=add-unknown-fields-to-the-schema} {add=[8487bfa0-6811-414a-9b82-01d4eb8005e1 (1501654816573620224)]} 0 36
INFO  - 2015-05-20 02:40:30.753; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={commit=false} {add=[8487bfa0-6811-414a-9b82-01d4eb8005e1]} 0 92
INFO  - 2015-05-20 02:40:35.333; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:35.333; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:35.334; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:35.335; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:35.335; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:35.335; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard2_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 2
INFO  - 2015-05-20 02:40:36.071; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrDeletionPolicy; SolrDeletionPolicy.onCommit: commits: num=2
	commit{dir=NRTCachingDirectory(MMapDirectory@/home/licett/solr/example/cloud/node1/solr/gettingstarted_shard1_replica1/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@3532a555; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_1,generation=1}
	commit{dir=NRTCachingDirectory(MMapDirectory@/home/licett/solr/example/cloud/node1/solr/gettingstarted_shard1_replica1/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@3532a555; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_2,generation=2}
INFO  - 2015-05-20 02:40:36.072; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrDeletionPolicy; newest commit generation = 2
INFO  - 2015-05-20 02:40:36.094; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.search.SolrIndexSearcher; Opening Searcher@6713eab1[gettingstarted_shard1_replica1] main
INFO  - 2015-05-20 02:40:36.099; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:36.100; [gettingstarted shard1  gettingstarted_shard1_replica1] org.apache.solr.core.QuerySenderListener; QuerySenderListener sending requests to Searcher@6713eab1[gettingstarted_shard1_replica1] main{ExitableDirectoryReader(UninvertingDirectoryReader(Uninverting(_0(5.1.0):C1)))}
INFO  - 2015-05-20 02:40:36.102; [gettingstarted shard1  gettingstarted_shard1_replica1] org.apache.solr.core.QuerySenderListener; QuerySenderListener done.
INFO  - 2015-05-20 02:40:36.104; [gettingstarted shard1  gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] Registered new searcher Searcher@6713eab1[gettingstarted_shard1_replica1] main{ExitableDirectoryReader(UninvertingDirectoryReader(Uninverting(_0(5.1.0):C1)))}
INFO  - 2015-05-20 02:40:36.105; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 772
INFO  - 2015-05-20 02:40:36.123; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:36.123; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:36.123; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:36.123; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:36.124; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:36.124; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:36.124; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:36.124; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:36.124; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard2_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 2
INFO  - 2015-05-20 02:40:36.125; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 3
INFO  - 2015-05-20 02:40:36.127; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={commit=true} {commit=,commit=} 0 797
INFO  - 2015-05-20 02:40:36.147; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/select params={distrib=false&wt=javabin&version=2&rows=10&df=_text_&fl=id&fl=score&shard.url=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/|http://127.0.1.1:7574/solr/gettingstarted_shard1_replica2/&NOW=1432089636135&start=0&shards.purpose=4&q=_id:55024e970dd4656673eb0147&isShard=true&fsv=true} hits=0 status=0 QTime=7 
INFO  - 2015-05-20 02:40:36.151; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/select params={q=_id:55024e970dd4656673eb0147&wt=json} hits=0 status=0 QTime=16 
INFO  - 2015-05-20 02:40:36.159; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:36.160; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:36.161; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:36.159; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:36.162; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:36.162; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:36.162; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:36.162; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard2_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 3
INFO  - 2015-05-20 02:40:36.163; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:36.164; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 6
INFO  - 2015-05-20 02:40:36.177; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:36.177; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:36.177; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2015-05-20 02:40:36.177; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:36.177; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; No uncommitted changes. Skipping IW.commit.
INFO  - 2015-05-20 02:40:36.177; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:36.178; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 2
INFO  - 2015-05-20 02:40:36.179; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.core.SolrCore; SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
INFO  - 2015-05-20 02:40:36.179; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2015-05-20 02:40:36.179; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard2_replica1] webapp=/solr path=/update params={waitSearcher=true&distrib.from=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/&update.distrib=FROMLEADER&openSearcher=true&commit=true&wt=javabin&expungeDeletes=false&commit_end_point=true&version=2&softCommit=false&update.chain=add-unknown-fields-to-the-schema} {commit=} 0 2
INFO  - 2015-05-20 02:40:36.187; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={commit=true} {commit=,commit=} 0 31
INFO  - 2015-05-20 02:40:36.193; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard2_replica1] webapp=/solr path=/select params={distrib=false&wt=javabin&version=2&rows=10&df=_text_&fl=id&fl=score&shard.url=http://127.0.1.1:8983/solr/gettingstarted_shard2_replica1/|http://127.0.1.1:7574/solr/gettingstarted_shard2_replica2/&NOW=1432089636190&start=0&shards.purpose=4&q=_id:55024e970dd4656673eb0147&isShard=true&fsv=true} hits=0 status=0 QTime=1 
INFO  - 2015-05-20 02:40:36.194; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/select params={distrib=false&wt=javabin&version=2&rows=10&df=_text_&fl=id&fl=score&shard.url=http://127.0.1.1:8983/solr/gettingstarted_shard1_replica1/|http://127.0.1.1:7574/solr/gettingstarted_shard1_replica2/&NOW=1432089636190&start=0&shards.purpose=4&q=_id:55024e970dd4656673eb0147&isShard=true&fsv=true} hits=0 status=0 QTime=1 
INFO  - 2015-05-20 02:40:36.195; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.core.SolrCore; [gettingstarted_shard1_replica1] webapp=/solr path=/select params={q=_id:55024e970dd4656673eb0147&wt=json} hits=0 status=0 QTime=5 
INFO  - 2015-05-20 02:40:36.228; [gettingstarted shard2 core_node2 gettingstarted_shard2_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard2_replica1] webapp=/solr path=/update params={distrib.from=http://127.0.1.1:7574/solr/gettingstarted_shard2_replica2/&update.distrib=FROMLEADER&wt=javabin&version=2&update.chain=add-unknown-fields-to-the-schema} {add=[92cb0c31-b691-44ee-b558-73eb0f66bdb4 (1501654822377488384)]} 0 4
INFO  - 2015-05-20 02:40:36.235; [gettingstarted shard1 core_node1 gettingstarted_shard1_replica1] org.apache.solr.update.processor.LogUpdateProcessor; [gettingstarted_shard1_replica1] webapp=/solr path=/update params={commit=false} {add=[92cb0c31-b691-44ee-b558-73eb0f66bdb4]} 0 29

**Comment by licett** [comment]
besides, I can not get the index of field "loc." but index of other fields is OK.

the record i insert is:
{ "_id" : ObjectId("555bf0df6c744bb33345aa6a"), "className" : "com.madao.server.common.mongoEntity.HistoryData", "uId" : 90, "teamId" : NumberLong(0), "speed" : 30, "elevation" : 5e-324, "acc" : 0, "loc" : [ 31.831942, 117.199812 ], "province" : "安徽省", "city" : "合肥市", "distance" : 0, "avgSpeed" : 0, "time" : "2015-05-20 10:26:39" }

field part of my schema is :
    
    <field name="uId" type="int" indexed="true" stored="true"/>
    <field name="teamId" type="long" indexed="true" stored="true"/>
    <field name="speed" type="float" indexed="true" stored="true"/>
    <field name="elevation" type="double" indexed="true" stored="true"/>
    <field name="acc" type="float" indexed="true" stored="true"/>
    <field name="province" type="string" indexed="true" stored="true"/>
    <field name="city" type="string" indexed="true" stored="true"/>
    <field name="loc" type="double" indexed="true" stored="true"/>

**Comment by llvtt** [comment]
It seems like you have two separate issues:

1. The "loc" field: Mongo Connector flattens arrays from MongoDB into separate fields. These new fields have the same name as the original field with the index within the array appended to the name following a ".". The "loc" field will become two fields: "loc.0" and "loc.1". Try adding these fields to schema.xml.
2. Since you're using `--auto-commit-interval=0`, you might be hitting a bug that was fixed since the 2.0.3 release (it will be in a forthcoming 2.0.4 release). Could you try the version from Github and see if that fixes this problem?

**Comment by licett** [comment]
1.this issue is solved, thanks!
2.I download the master version zip from the mainpage, and the changelog says its current version is 2.0.3. So, in your opinon, I must wait for a while (2.0.4)?

**Comment by llvtt** [comment]
If you downloaded the zip from Github, you're good to go. The changelog hasn't been updated for 2.0.4 yet.

**Comment by licett** [comment]
strangely , I delete the oplog.timestamp, now all index is fine.....

**Comment by licett** [comment]
pls close this issue, delte the file oplog.timestamp makes all fine

**Comment by anshuljohri** [comment]
Hi Luke,

I am also facing the same issue. Mongo connector works fine when a new record is inserted but its not working fine when an old record is updated. As per your instruction on this thread I again downloaded the zip version of mongo connector from git and installed it. But it does not solve the issue. 

Please comment. On this. This is the production issue for me for my site http://www.rentomo.com
